#!/bin/bash
# gen-stamp.sh — regenerate src/BuildStamp.g.cs before every build (csproj BeforeBuild target).
# Stamp = git short sha; if the tree is DIRTY, "+HHMM" is appended so every rebuild of
# work-in-progress produces a FRESH stamp. This kills the 'stale build masquerade' failure
# class (two machines / a running game on an old DLL while everyone reads new src) without
# anyone remembering to bump a marker by hand.
cd "$(dirname "$0")"
h=$(git rev-parse --short HEAD 2>/dev/null || echo nogit)
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then s="$h+$(date +%H%M)"; else s="$h"; fi
cat > src/BuildStamp.g.cs <<EOF
// AUTO-GENERATED by gen-stamp.sh (BeforeBuild) — do not edit; gitignored.
namespace RaftMovableStorage { internal static class BuildStamp { public const string Value = "$s"; } }
EOF
echo "$s"
